### ISSUE TITLE
Sed in different unixes

### ISSUE THREAD

**Issue by pjaspers** [pjaspers/beech#1]
# TODO correct parameter for extended regexes => BSD: `sed -E`; GNU: `sed -r`

**Comment by To1ne** [comment]
The current `sed` does not work, because it does not treat the characters as special.

A possible solution could be, but this would add a lot of line of code:
http://stackoverflow.com/questions/1676426/how-to-check-the-ls-version

**Comment by To1ne** [comment]
Probably better error handling should be done.
1. The exit code from curl should be handled
2. When <error> is found in the XML returned by Twitter.com, a non-zero value should be returned
